export const REQUEST_NEW_TASK = 'REQUEST_NEW_TASK';
export const CREATE_NEW_TASK = 'CREATE_NEW_TASK';
export const SET_TASK_COMPLETE = 'SET_TASK_COMPLETE';
export const SET_TASK_NAME = 'SET_TASK_NAME';
export const SET_TASK_GROUP = 'SET_TASK_GROUP';
